apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: temp
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Datalab Terraform Module
    source:
      repo: https://github.com/bdpanigrahi-create/temp.git
      sourceType: git
    description: {}
  content:
    subBlueprints:
      - name: iap_firewall
        location: modules/iap_firewall
      - name: instance
        location: modules/instance
      - name: template_files
        location: modules/template_files
    examples:
      - name: advance
        location: examples/advance
      - name: basic
        location: examples/basic
  interfaces: {}
  requirements:
    roles:
      - level: Project
