# main.tf

# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/ide-exp/locations/us-central1/spaces/default-space/applicationTemplates/billing-processor-template-b4k8d

module "billing-lb-backend-b4k8d" {
  source     = "github.com/GoogleCloudPlatform/terraform-google-regional-lb-http//modules/backend?ref=v0.6.1"
  project_id = "ide-exp"
  region     = "us-central1"
  name       = "billing-lb-backend-b4k8d"
  serverless_neg_backends = [
    {
      capacity_scaler = 1
      region          = module.billing-processor-b4k8d.location
      service_name    = module.billing-processor-b4k8d.service_name
      service_version = ""
      type            = "cloud-run"
    },
  ]
}
module "billing-lb-frontend-b4k8d" {
  source        = "github.com/GoogleCloudPlatform/terraform-google-regional-lb-http//modules/frontend?ref=v0.10.0"
  project_id    = "ide-exp"
  region        = "us-central1"
  name          = "billing-lb-frontend-b4k8d"
  network       = "default"
  url_map_input = module.billing-lb-backend-b4k8d.backend_service_info
}
module "billing-processor-b4k8d" {
  source       = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.30.0"
  project_id   = "ide-exp"
  location     = "us-central1"
  service_name = "billing-processor-b4k8d"
  containers = [
    {
      container_image = "us-central1-docker.pkg.dev/ide-exp/billing-processor-repo/billing-processor:v2"
      env_vars = {
        billing_logs_topic_TOPIC_ID = module.billing-logs-topic.id
      }
      ports = {
        container_port = 8080
      }
    },
  ]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = [
    "roles/pubsub.publisher",
    "roles/pubsub.subscriber",
    "roles/run.invoker",
  ]
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "billing-logs-topic" {
  source             = "github.com/terraform-google-modules/terraform-google-pubsub?ref=v8.6.0"
  project_id         = "ide-exp"
  topic              = "billing-logs"
  push_subscriptions = concat([{ "oidc_service_account_email" = module.billing-processor-b4k8d.service_account_id.email, "push_endpoint" = module.billing-processor-b4k8d.service_uri, "name" = module.billing-processor-b4k8d.apphub_service_uri.service_id }], [{ "name" = module.alerting-server-b4k8d.apphub_service_uri.service_id, "oidc_service_account_email" = module.alerting-server-b4k8d.service_account_id.email, "push_endpoint" = module.alerting-server-b4k8d.service_uri }])
  pull_subscriptions = concat([{ "name" = module.billing-processor-b4k8d.service_name, "service_account" = module.billing-processor-b4k8d.service_account_id.email }], [{ "name" = module.alerting-server-b4k8d.service_name, "service_account" = module.alerting-server-b4k8d.service_account_id.email }])
  bigquery_subscriptions = [\n    {\n      name  = module.billing-logs-dataset-b4k8d.table_ids[0]\n      table = \"${module.billing-logs-dataset-b4k8d.project}:${module.billing-logs-dataset-b4k8d.env_vars.BIGQUERY_DATASET}.${module.billing-logs-dataset-b4k8d.table_ids[0]}\"\n    },\n  ]
}
module "billing-logs-dataset-b4k8d" {
  source     = "github.com/terraform-google-modules/terraform-google-bigquery?ref=v10.2.1"
  dataset_id = "billing_logs_dataset_b4k8d"
  project_id = "ide-exp"
  tables = [\n    {\n      schema   = \"[{\\\"name\\\":\\\"data\\\",\\\"type\\\":\\\"STRING\\\"}]\"\n      table_id = \"billing_logs_table_b4k8d\"\n    },\n  ]
}
module "log-reader-server-b4k8d" {
  source       = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.30.0"
  project_id   = "ide-exp"
  location     = "us-central1"
  service_name = "log-reader-server-b4k8d"
  containers = [\n    {\n      container_image = \"us-central1-docker.pkg.dev/ide-exp/billing-processor-repo/log-reader-server:v1\"\n      env_vars = {\n        billing_logs_dataset_b4k8d_BIGQUERY_DATASET            = module.billing-logs-dataset-b4k8d.env_vars.BIGQUERY_DATASET\n        billing_logs_dataset_b4k8d_BIGQUERY_EXTERNAL_TABLES    = module.billing-logs-dataset-b4k8d.env_vars.BIGQUERY_EXTERNAL_TABLES\n        billing_logs_dataset_b4k8d_BIGQUERY_MATERIALIZED_VIEWS = module.billing-logs-dataset-b4k8d.env_vars.BIGQUERY_MATERIALIZED_VIEWS\n        billing_logs_dataset_b4k8d_BIGQUERY_ROUTINES           = module.billing-logs-dataset-b4k8d.env_vars.BIGQUERY_ROUTINES\n        billing_logs_dataset_b4k8d_BIGQUERY_TABLES             = module.billing-logs-dataset-b4k8d.env_vars.BIGQUERY_TABLES\n        billing_logs_dataset_b4k8d_BIGQUERY_VIEWS              = module.billing-logs-dataset-b4k8d.env_vars.BIGQUERY_VIEWS\n      }\n    },\n  ]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = [\n    \"roles/bigquery.dataEditor\",\n  ]
  vpc_access = {\n    egress = \"PRIVATE_RANGES_ONLY\"\n    network_interfaces = {\n      network    = \"default\"\n      subnetwork = \"default\"\n    }\n  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {\n    min_instance_count = 0\n  }
  template_scaling = {\n    min_instance_count = 0\n  }
}
module "alerting-server-b4k8d" {
  source       = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.30.0"
  project_id   = "ide-exp"
  location     = "us-central1"
  service_name = "alerting-server-b4k8d"
  containers = [\n    {\n      container_image = \"us-central1-docker.pkg.dev/ide-exp/billing-processor-repo/alerting-server:v1\"\n      env_vars = {\n        billing_logs_topic_TOPIC_ID = module.billing-logs-topic.id\n      }\n    },\n  ]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = [\n    \"roles/pubsub.publisher\",\n    \"roles/pubsub.subscriber\",\n    \"roles/run.invoker\",\n  ]
  vpc_access = {\n    egress = \"PRIVATE_RANGES_ONLY\"\n    network_interfaces = {\n      network    = \"default\"\n      subnetwork = \"default\"\n    }\n  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {\n    min_instance_count = 0\n  }
  template_scaling = {\n    min_instance_count = 0\n  }
}
