# outputs.tf

# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/ide-exp/locations/us-central1/spaces/default-space/applicationTemplates/billing-processor-template-b4k8d

output "billing-lb-frontend-b4k8d_external_ip" {
  description = "The external IPv4 assigned to the fowarding rule."
  value       = module.billing-lb-frontend-b4k8d.external_ip
}
output "billing-lb-frontend-b4k8d_ip_address_http" {
  description = "The internal/external IP address assigned to the HTTP forwarding rule."
  value       = module.billing-lb-frontend-b4k8d.ip_address_http
}
output "billing-lb-frontend-b4k8d_ip_address_https" {
  description = "The internal/external IP address assigned to the HTTPS forwarding rule."
  value       = module.billing-lb-frontend-b4k8d.ip_address_https
}
output "billing-processor-b4k8d_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.billing-processor-b4k8d.service_uri
}
output "log-reader-server-b4k8d_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.log-reader-server-b4k8d.service_uri
}
output "alerting-server-b4k8d_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.alerting-server-b4k8d.service_uri
}
