# terraform.tfvars

# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/ide-exp/locations/us-central1/spaces/default-space/applicationTemplates/billing-processor-template-b4k8d
